apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: team12deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: team12minecraft
    spec:
      containers:
      - name: minecraft-server
        image: challenge1.azurecr.io/minecraft-server:1.0
        env:
        - name: EULA
          value: "TRUE"
        ports:
        - containerPort: 25565
          name: minecraftserver
        - containerPort: 25575
          name: minecraftrcon
      imagePullSecrets:
        - name: supersecret
---
apiVersion: v1
kind: Service
metadata:
  name: team12service
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 25565
  - name: rcon 
    port: 25575
  selector:
    app: team12minecraft
